# Generated by Django 4.0.3 on 2022-05-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='technician',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='service',
            name='vin',
        ),
    ]
